Power BI firewall blocker
DTS-STN/CDP-Lessons-Learned pull request #10
Opened 2022-01-18 18:08 UTC by arpit-dhindsa

Document Firewall Blocker, workaround and debugging steps

2022-01-19 13:30 UTC, s-laugh requested changes
This is an excellent start on documenting the problem!
I still have some questions though
- What other workarounds might there be?
- What do we actually need help determining about the blocker specifically? Do you see any other un-answered questions?

2022-01-19 13:30 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +This workaround was used for the Nov29 deliverable. If access to ESDC Azure gets restricted to VPN, then users will not be able to connect to the source and create Power BI reports as Power BI Deskto
We'll need to expand on this - The requirement isn't that the data is on VPN but on ESDC provided equipment. So an ESDC provided laptop, disconnected from VPN needs to be explored here. (I understand you can't do this as you only have SAVE-D).

2022-01-19 13:30 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +Azure Synapse Analytics (dedicated SQL pool only) supports Private Link which allows to connect Azure SQL DW via a private endpoint (a private IP address within a specific Azure VNet and subnet). Cre
(see [this link]() for details) - link is missing

2022-01-19 13:30 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +One workaround is to connect to Azure Synapse Analytics or Databricks Spark Tables from Power BI Desktop off-network (off-VPN) to build reports. Once the report has been created, log back into VPN an
How does this impact auto/scheduled-refresh of the data?

2022-01-28 16:04 UTC, s-laugh requested changes
Some good improvements in here. I'm still getting confused with some things, specifically where the re-fresh points are breaking (or working). Some clarification would really help.

2022-01-28 16:04 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +The following debugging options can be tried to help resolve this problem. The first and second option may not require any assistance from the security team but, third option will need full involvmen
Where any of these options attempted?
If yes, the results should be shared here.
If no, we can approve and merge, but the debugging should be done as part of the story/blocker.

2022-01-28 17:58 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +One workaround to building Power BI reports is to connect to Azure Synapse Analytics and Databricks Spark Tables from Power BI Desktop on ESDC provided laptop disconnected from VPN. Once the report h
Right now the data tables are only being stored in Azure Synapse Analytics so, currently we only need one connection which is to Synapse Analytics. But, in future if we have tables residing in Databricks, we will need to establish connection to the Databricks spark database. Hence, I tested connection to both the services.

2022-01-28 18:14 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +One workaround to building Power BI reports is to connect to Azure Synapse Analytics and Databricks Spark Tables from Power BI Desktop on ESDC provided laptop disconnected from VPN. Once the report h
I will add those.

2022-01-28 21:33 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +This workaround was used for the Nov29 deliverable. If access to Azure gets restricted to VPN, then users will not be able to connect to the source and create Power BI reports. Power BI Desktop appli
Sorry for the confusion, I meant if connecting to synapse analytics and databricks from power bi desktop gets unpermitted off-vpn then the workaround will not work. I made this change to be clear.

2022-01-28 22:08 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +The following debugging options can be tried to help resolve this problem. The first and second option may not require any assistance from the security team but, third option will need full involvmen
These were not attempted. They will require permissions to:
- create new resources (like azure vnet)
- create firewall rules on Synapse
and may require additional permissions.

2022-01-31 13:19 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +One workaround to building Power BI reports is to connect to Azure Synapse Analytics and Databricks Spark Tables from Power BI Desktop on ESDC provided laptop disconnected from VPN. Once the report h
Okay, can you clarify that in the document then? Our arch points us to only needing connections with the Synapse DW, so that should be the suggested workaround.

2022-01-31 13:22 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +This workaround was used for the Nov29 deliverable. If access to Azure gets restricted to VPN, then users will not be able to connect to the source and create Power BI reports. Power BI Desktop appli
This update only has me more confused, can you try reducing the use of negatives here, like "unpermitted"

2022-01-31 13:25 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +The following debugging options can be tried to help resolve this problem. The first and second option may not require any assistance from the security team but, third option will need full involvmen
Okay, I've opened a sub-task SAEB-1137 to action these debugging steps.

2022-01-31 16:45 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +One workaround to building Power BI reports is to connect to Azure Synapse Analytics and Databricks Spark Tables from Power BI Desktop on ESDC provided laptop disconnected from VPN. Once the report h
yes, I can do that. But we are facing issues connecting to databricks spark tables from power bi desktop when on-vpn and on vdi as mentioned in this document.

2022-01-31 17:16 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +The following debugging options can be tried to help resolve this problem. The first and second option may not require any assistance from the security team but, third option will need full involvmen
Ok, thanks Shaun. This will likely move to next sprint.

2022-01-31 17:53 UTC, s-laugh requested changes
Just one element that I feel needs some strong clarification, see comment.
Also re-noting, issue SAEB-1137 was created to debug the problem, based on some of this documentation.

2022-01-31 17:53 UTC, s-laugh commented on Power BI Firewall Blocker.md
> +### Data Refresh in Power BI Desktop and Report Server
I think this section still needs some work. If I'm understanding it correctly, PowerBI reports can not be auto refreshed. This has a huge impact on our ability to service basic functions as a reporting suite. Assuming I'm understanding that correctly, this section needs to make the block, and the impacts of the block extremely clear. - This is how we will have any ground to request changes to the firewall restrictions.

2022-01-31 18:11 UTC, arpit-dhindsa commented on Power BI Firewall Blocker.md
> +### Data Refresh in Power BI Desktop and Report Server
that is correct, I will make this modification

2022-02-02 13:52 UTC, s-laugh approved these changes

2022-02-02 17:36 UTC, merged