Saeb dev 20220117 aa to azure python class
DTS-STN/CDP-Lessons-Learned pull request #11
Opened 2022-01-19 16:34 UTC by JuntaoZ-NC

This PR is meant to be the first PR to provide step-by-step tutorial for the AA-to-Azure-Python-Wrapper Class created.

Here are the items included in this PR:

1. Readme files
2. Requirements file
3. sample codes
4. AA-to-Azure-Python-Wrapper Class itself

Readme files
1.General Readme that provides insights to the integration from AA to Azure finally Power BI
2.Azure specific Readme that shows step by step guidance related to Azure
2.PowerBI specific Readme that shows step by step guidance related to Power BI

Requirements file
requirements.txt file for python to install dependencies

sample codes
1.Jupyter notebook code sample to utilize the Class
2.ADF pipeline to integrate notebook with other activities

AA-to-Azure-Python-Wrapper Class
analytics_client Class that is designed to be imported as a wrapper to request AA data

2022-01-20 15:06 UTC, Jordan-Morrison approved these changes

2022-02-22 17:30 UTC, alex-solo approved these changes
LGTM

2022-02-25 16:49 UTC, s-laugh requested changes
The commits need to be signed (see here to update https://stackoverflow.com/questions/13043357/git-sign-off-previous-commits), and this is removing a bunch of other files from other work.

2022-02-25 16:51 UTC, s-laugh commented
Also you are adding a lot of sample code, which is great, but if it's already implemented in another repository (aka AP-Databricks) it would be better to link there instead of copying it here.

2022-02-25 17:23 UTC, JuntaoZ-NC commented
updated ms.date and update readme to ref AP repo

2022-02-25 18:05 UTC, s-laugh requested changes
The commits are still not verified (PR can't be merged until they are).
There's still a number of files that I believe should be links to the repositories and not duplicated here - I commented on them individually.
This PR still is deleting some files that it shouldn't - I've also commented on those individually.

2022-02-25 18:05 UTC, s-laugh commented on Performance Dashboard.md
> -# Performance Dashboard
This file shouldn't be deleted.

2022-02-25 18:05 UTC, s-laugh commented on SAEB Architecture Design.md
> -# SAEB Architecture Design
This file shouldn't be deleted.

2022-02-25 18:05 UTC, s-laugh commented on SC Labs.md
> -# Lessons Learned
This file shouldn't be deleted.

2022-02-25 18:29 UTC, JuntaoZ-NC commented on Adobe-Azure-analytics-api-v2.0/examples/ADFpipeline/oas_take_up.json
> +{
resolved here :https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/c6ab90ed62949e515b0febb7ad9e442bc8626196

2022-02-25 18:29 UTC, JuntaoZ-NC commented on Adobe-Azure-analytics-api-v2.0/examples/ADFpipeline/sclabs_site_analytics.json
> +{
resolved here https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/c6ab90ed62949e515b0febb7ad9e442bc8626196

2022-02-25 18:29 UTC, JuntaoZ-NC commented on Adobe-Azure-analytics-api-v2.0/examples/DatabricksNotebook/Azurepipeline.md
> +
resolved here https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/c6ab90ed62949e515b0febb7ad9e442bc8626196

2022-02-25 18:31 UTC, JuntaoZ-NC commented on Adobe-Azure-analytics-api-v2.0/examples/JupyterNotebook/JWTExample.ipynb
> +{"cells":[{"cell_type":"code","execution_count":null,"metadata":{"application/vnd.databricks.v1+cell":{"inputWidgets":{},"nuid":"4dd5cd33-e410-4a2d-9ffd-1f00a32ec5a1","showTitle":false,"title":""}},"
No, we do not have Jupyter Notebooks in the cloud ,and I used Jupyter in my local machine ,thus removed sample code here :https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/c6ab90ed62949e515b0febb7ad9e442bc8626196

2022-02-25 18:52 UTC, JuntaoZ-NC commented on Performance Dashboard.md
> -# Performance Dashboard
Apologies for almost losing 3 documentations due to rebasing on outdated branch ,
Restored 3 documentations here https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/75e8489d3e2d3650d968170672c5b9da3c254962
https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/4a190ef293362e9fd10a72afebb7ccbfd582e9c8

2022-02-25 18:53 UTC, JuntaoZ-NC commented on SAEB Architecture Design.md
> -# SAEB Architecture Design
Apologies for almost losing 3 documentations due to rebasing on outdated branch ,
Restored 3 documentations here https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/75e8489d3e2d3650d968170672c5b9da3c254962
https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/4a190ef293362e9fd10a72afebb7ccbfd582e9c8

2022-02-25 18:53 UTC, JuntaoZ-NC commented on SC Labs.md
> -# Lessons Learned
Apologies for almost losing 3 documentations due to rebasing on outdated branch ,
Restored 3 documentations here https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/75e8489d3e2d3650d968170672c5b9da3c254962
https://github.com/DTS-STN/CDP-Lessons-Learned/pull/11/commits/4a190ef293362e9fd10a72afebb7ccbfd582e9c8

2022-02-25 20:37 UTC, JuntaoZ-NC commented
PR closed due to duplicate commit ,opened another PR https://github.com/DTS-STN/CDP-Lessons-Learned/pull/13

2022-02-25 20:37 UTC, closed without merging