Document saeb architecture
DTS-STN/CDP-Lessons-Learned pull request #2
Opened 2021-09-14 14:46 UTC by arpit-dhindsa

2021-09-14 15:18 UTC, s-laugh requested changes
This is helpful to see what's being worked on and towards. But I would really like to take 30-60 min to have you actually show and walk me though the configurations and code of the tools themselves.

I've also added a number of comments where I'm looking for more clarity in the documentation itself.

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +The exercise aimed to use OAS dataset however, due to delayed access to the On-Prem Oracle Data Lake (Sandbox), an unclassified data was used that was already present in the blob storage. To do this
Access isn't the only issue here, its also having a protected environment to host the data and ensuring data is declassified where applicable. I don't think this should have been part of the original scope. Can discuss more.

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +-	Create data pipeline using Azure Synapse
```suggestion
- Create data pipeline using Azure Synapse
```

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +## Goals
You should identify here that we wanted to ingest and transform the data using the pipelines.

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +Before building a data factory pipeline, linked service was created for Databricks Workspace and Azure Data Lake Gen2 storage account. The pipeline runs Databricks notebook that reads data from stora
Do you identify elsewhere what the connection issues are? Can you point to them here. Also please separate what the actual pipeline was created and use, and what the indented pipeline was.

As well can you clarify what "live data refresh" actually means? What triggers the refresh, how often?

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +   - _Solution:_ Add user and synapse workspace to ACLs in Data Lake storage and give Read, Write and Execute permissions on container as the database tables are stored under a synapse directory that
ACLs? Can you please type out the acronym.

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +          - Grant Azure Synapse Reader and Data Access role on Data Lake Storage Account as this will only allow read/write access to the data contained in a storage account.
```suggestion
          - Grant `Azure Synapse` `Reader and Data Access` role on 'Data Lake Storage Account' as this will only allow read/write access to the data contained in a storage account.
```
Can you make it clear throughout the document, what the components are, their names and the access levels and what that actually entails (the last part you mostly have).

2021-09-14 15:18 UTC, s-laugh commented on SAEB Architecture Design.md
> +## Tech Comparisons
Can we make this section more feature focused, in possibly a table format.

Describe the feature, and describe and clearly indicate how each tool does or does not meet that feature.

2021-09-14 15:20 UTC, s-laugh commented on SAEB Architecture Design.md
> +![Data Flow using ADF and Databricks](https://github.com/DTS-STN/CDP-Lessons-Learned/blob/main/Data_Flow_2.png)
You talk about an additional connection being made between Data Factory and Databricks but the diagram doesn't show that very clearly.

2021-09-14 15:22 UTC, s-laugh commented on SAEB Architecture Design.md
> +![Data Flow using ADF and Databricks](https://github.com/DTS-STN/CDP-Lessons-Learned/blob/main/Data_Flow_2.png)
```suggestion
![Data Flow using ADF and Databricks](Data_Flow_2.png)
```

2021-09-14 15:22 UTC, s-laugh commented on SAEB Architecture Design.md
> +![Data Flow using Azure Synapse](https://github.com/DTS-STN/CDP-Lessons-Learned/blob/main/Data_Flow_1.png)
```suggestion
![Data Flow using Azure Synapse](Data_Flow_1.png)
```

2021-09-14 15:39 UTC, s-laugh commented on SAEB Architecture Design.md
> +Azure Synapse Analytics offers codeless data integration capabilities like Azure Data Factory. Both offer the ability to build a data integration pipeline using graphical user interface without writi
SSIS? Please type out the acronym

2021-09-14 22:45 UTC, arpit-dhindsa commented on SAEB Architecture Design.md
> +![Data Flow using ADF and Databricks](https://github.com/DTS-STN/CDP-Lessons-Learned/blob/main/Data_Flow_2.png)
@s-laugh, are you referring to linked service?

2021-09-15 16:32 UTC, s-laugh commented on SAEB Architecture Design.md
> +![Data Flow using ADF and Databricks](https://github.com/DTS-STN/CDP-Lessons-Learned/blob/main/Data_Flow_2.png)
yeah exactly, I'm just not getting a clear understanding between the diagram and the description provided.

2021-09-17 13:32 UTC, s-laugh reviewed
These changes are wonderful, I'm just left with one question about the Data Factory pipeline.
(Also I'm hoping leaving this as "comment" won't block the PR from being merged once approved by someone else)

2021-09-17 13:32 UTC, s-laugh commented on SAEB Architecture Design.md
> +### Azure Data Factory and Azure Databricks
The changes you've made here really help separate the different things going on, and it's great!
BUT I'm still left wondering, how does Data Factory fit into this pipeline that was created?

2021-09-17 14:46 UTC, arpit-dhindsa commented on SAEB Architecture Design.md
> +### Azure Data Factory and Azure Databricks
Data Factory is an orchestration tool that executes Databricks notebook that reads, transforms and writes data to the lake.

2021-09-17 14:56 UTC, s-laugh commented on SAEB Architecture Design.md
> +### Azure Data Factory and Azure Databricks
That helps, can you just copy that line into the doc and I'll approve.

2021-09-17 15:16 UTC, s-laugh approved these changes

2021-09-17 16:07 UTC, merged